'use client';

import { useEffect } from 'react';
import Newsletter from '../Newsletter';

const Content = () => {
  useEffect(() => {
    // Add event listener for Bootstrap accordion shown event
    const accordionItems = document.querySelectorAll('.accordion-item');
    accordionItems.forEach((item) => {
      item.addEventListener('shown.bs.collapse', () => {
        // Scroll the item to the top of the screen
        const itemTop = item.getBoundingClientRect().top + window.scrollY;
        window.scrollTo(0, itemTop - 100);
      });
    });
  }, []);

  return (
    <div className="container my-5">
      <div className="row">
        <div className="col-lg-7 mx-auto">
          <div className="accordion" id="accordionExample">
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse1"
                  aria-expanded="true"
                  aria-controls="collapse1"
                >
                  1. GENERAL
                </button>
              </h2>
              <div
                id="collapse1"
                className="accordion-collapse collapse show"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    In terms of Information Technology Act, 2000, this document
                    is an electronic record. Being generated by a computer
                    system it does not require any physical or digital
                    signatures.
                  </p>

                  <p>
                    <b>
                      This document is published in accordance with the
                      provisions of Rule 3 (1) of the Information Technology
                      (Intermediaries guidelines) Rules, 2011 that require
                      publishing the rules and regulations, privacy policy and
                      Terms of Use for access or usage of itsyourskills.
                    </b>
                  </p>

                  <p>
                    The website{' '}
                    <a href="https://www.itsyourskills.com">
                      itsyourskills.com
                    </a>
                    , its web applications and related services, is the property
                    of IYS Skills Tech Private Ltd, a Company incorporated under
                    the Companies Act, 1956, with its Registered Office at No
                    598, Alagirisamy salai, K.K. Nagar, Chennai – 600 078.
                  </p>

                  <p>
                    The use of this software by you is solely governed by this
                    policy and any policy or agreement so mentioned by this
                    Terms of Use. You have read and agreed to all of the
                    policies so binding on you and you are contracting with{' '}
                    <b>IYS Skills Tech Private Ltd.</b>
                    for legally binding obligations with{' '}
                    <b>IYS Skills Tech Private Ltd.</b>
                  </p>

                  <p>
                    For the purpose of these Terms of Use, wherever the context
                    so requires:
                  </p>

                  <ul>
                    <li>
                      <strong>“You” or “User”</strong> shall mean any natural or
                      legal person who has agreed to become a member on the
                      Website by providing registration data while registering
                      on the Website, uses the Software by providing
                      Registration Data while registering for the software /
                      website, uses the website, provides skills through the
                      Skills Profile Engine API or the applications built on it,
                      or any person who browses the site.
                    </li>
                    <li>
                      <strong>“We”, “Us”, “Our”</strong> means IYS Skills Tech
                      Private Ltd.
                    </li>
                    <li>
                      <strong>“Content”</strong> means the text, documents,
                      information, data, articles, images, photographs,
                      graphics, software, applications, video recordings, audio
                      recordings, sounds, designs, features, and other materials
                      that are available on the Site. <strong>“Content”</strong>{' '}
                      also includes Marks, and generally all information that is
                      displayed to the user on the website.
                    </li>
                    <li>
                      <strong>“Mark”</strong> means trademark, trade name,
                      service mark, trade dress, logo, custom graphics or icon.
                    </li>
                    <li>
                      <strong>“Member”</strong> means an individual who has
                      registered with the Site. Members choose a Member ID and a
                      password.
                    </li>
                    <li>
                      <strong>“Member ID”</strong> means the email address you
                      use (with your password) to login to our Site.
                    </li>
                    <li>
                      <strong>“Recruiter / Vendors”</strong> means licensors,
                      suppliers, information providers, Companies, firms,
                      natural and juristic persons, and other vendors operating
                      through the website, obtaining information through the
                      website or otherwise related to the entity owning
                      itsyourskills portal.
                    </li>
                    <li>
                      The terms{' '}
                      <strong>Site, Marks, Content and Services</strong> do not
                      include the sites, marks, content, or services that are
                      available through a link from the Site. Their use is
                      subject to the terms set forth by their respective owners
                      or operations, on the third party’s website.
                    </li>
                    <li>
                      <strong>“Site”</strong> means{' '}
                      <a href="https://www.itsyourskills.com">
                        www.itsyourskills.com
                      </a>
                      , its respective sub-sites, together with the respective
                      Content, Marks, Products and Services available from these
                      sites and sub-sites.
                    </li>
                    <li>
                      <strong>“Employment”</strong> means any employment
                      obtained by the user through the site, regardless of the
                      terms, nature or duration of such employment. It is hereby
                      specified that consulting services / freelance services /
                      independent contractor services shall, for the purposes of
                      these and other terms, be deemed to come under the purview
                      of employment.
                    </li>
                  </ul>

                  <p>
                    You will be subject to the rules, guidelines, policies,
                    terms, and conditions applicable to any service that is
                    provided by this software, and they shall be deemed to be
                    incorporated into this Terms of Use and shall be considered
                    as part and parcel of this Terms of Use.
                  </p>

                  <p>
                    We hold the sole right to modify the Terms of Use without
                    prior permission from You or informing You. The relationship
                    creates on You a duty to periodically check the terms and
                    stay updated on its requirements. If You continue to use the
                    software following such a change, this is deemed as consent
                    by You to the so amended policies. As long as You comply
                    with these Terms of Use, We grant You a personal,
                    non-exclusive, non-transferable, limited privilege to enter
                    and use the Software.
                  </p>

                  <p>
                    By impliedly or expressly accepting these Terms of Use, You
                    also accept and agree to be bound by other IYS Skills Tech
                    Private Ltd Policies, inter alia Privacy Policy, which would
                    be amended from time to time.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse2"
                  aria-expanded="false"
                  aria-controls="collapse2"
                >
                  2. ABOUT US
                </button>
              </h2>
              <div
                id="collapse2"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    Itsyourskills offers web tools, applications, and platforms
                    revolving around:
                  </p>

                  <ol>
                    <li>mapping and measuring of skills;</li>
                    <li>recruitment and development of skills; and</li>
                    <li>
                      Offering of services related to recruitment and
                      development of skills.
                    </li>
                  </ol>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse3"
                  aria-expanded="false"
                  aria-controls="collapse3"
                >
                  3. MEMBERSHIP AND TERMS OF ACCEPTANCE
                </button>
              </h2>
              <div
                id="collapse3"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    The use of this software is available only to designated
                    users who have registered by providing a set of secure login
                    credentials. To become a registered Member, you are required
                    to answer a limited number of mandatory questions. Answers
                    to additional questions are optional. You represent and
                    warrant that all information supplied to us about yourself
                    and others is true and accurate.
                  </p>

                  <p>
                    Minors and individuals not competent to Contract (as defined
                    under the laws of their jurisdiction or residence) are not
                    eligible to register for, use the services of, or apply for
                    jobs available on the Site. Notwithstanding the
                    aforementioned, it is hereby specified that the usage of the
                    site and its services by any individual below the age of
                    thirteen years is strictly prohibited.
                  </p>

                  <p>
                    The Product <b>‘itsyourskills’</b> itself is hosted on{' '}
                    <a href="https://www.itsyourskills.com">
                      www.itsyourskills.com
                    </a>
                    , which consists of all the details about the features,
                    utilities, and functionality of the product along with
                    access entry log in portal.
                  </p>

                  <p>
                    As a designated user, You are solely responsible for
                    protecting the confidentiality of your username and
                    password, and any activity under the account will be deemed
                    to have been done by you. In the event you provide us with
                    false and inaccurate details or We have reasons to believe
                    so, We hold the right to permanently suspend your account.
                  </p>

                  <p>
                    We reserve the right to update the Terms of Use at any time
                    without notice to you. The most current version of the Terms
                    of Use can be reviewed by clicking on the “Terms of Use”
                    hypertext link provided on the website.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse4"
                  aria-expanded="false"
                  aria-controls="collapse4"
                >
                  4. WEBSITE AS AN INTERMEDIARY PLATFORM
                </button>
              </h2>
              <div
                id="collapse4"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    The Website is a platform that Users utilize to meet and
                    interact with one another and Vendors / Recruiters for their
                    transactions. We act as aggregators who display to you the
                    vendors and recruiters best suited to your needs, based on
                    the skills you have provided to us / updated on the site /
                    updated on the Skills Profile Engine API, or applications
                    built on it. However, should you choose to proceed with a
                    vendor / recruiter displayed / identified by us, we are not
                    a party to such interaction and take no liability that
                    arises from any such communication.
                  </p>

                  <ol>
                    <li>
                      <p>
                        All communication which inter alia includes the
                        employment, its terms, your obligations, the vendor’s
                        obligations, etc. is the outcome of the communication
                        between the vendor / recruiter and You. We do not have
                        any control over such information and play no
                        determinative role in the finalization of the same and
                        hence do not stand liable for the outcomes of such
                        communication.
                      </p>
                    </li>
                    <li>
                      <p>
                        We do not endorse any of the vendors / recruiters
                        displayed to you on the website, nor place any guarantee
                        as to their nature, quality, reliability, etc.
                      </p>
                    </li>
                    <li>
                      <p>
                        Subject to the above sub-clauses, a contract exists
                        between the Vendor and the User, and as such any breach
                        of contract and any claim arising from such breach is
                        the subject matter of the Vendor / recruiter and the
                        User alone, and we are in no way a party to such breach
                        or involved in any suit arising from the said breach.
                      </p>
                    </li>
                    <li>
                      <p>
                        As the contract is limited to the User and the vendor /
                        recruiter, we are in no way liable for any deficiency of
                        service that may arise which includes and is not limited
                        to, services not meeting expectations of the vendor /
                        recruiter, and poor quality, non-adherence to the terms
                        of employment discussed, etc.
                      </p>
                    </li>
                  </ol>

                  <p>
                    You agree to abide by the terms and conditions imposed by
                    any provider, including compliance with all rules and
                    restrictions regarding the Employment.
                  </p>

                  <p>
                    <strong>Disclaimer:</strong> Due to some technical issue or
                    typographical error, information related to employments as
                    is reflected on the website may be incorrect.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse5"
                  aria-expanded="false"
                  aria-controls="collapse5"
                >
                  5. COMMUNICATIONS
                </button>
              </h2>
              <div
                id="collapse5"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    By using this software, it is deemed that you have consented
                    to receiving e-mails, calls, autodialed and/or pre-recorded
                    message calls from Us or from recruiters on the portal at
                    any time. This includes contacting you through information
                    received through other API applications we use on the
                    website. The use of this software is also your consent to
                    receive SMS’s at any time we deem fit. This consent to be
                    contacted is for purposes that include and are not limited
                    to clarification calls and marketing and promotional calls.
                  </p>

                  <p>
                    You hereby unconditionally consent that such communications
                    via SMS and/or voice call are:
                  </p>

                  <ol>
                    <li>Upon your request and authorization,</li>
                    <li>
                      ‘Transactional’ and not an ‘unsolicited commercial
                      communication’ as per the guidelines of Telecom Regulation
                      Authority of India (TRAI), and
                    </li>
                    <li>
                      In compliance with the relevant guidelines of TRAI or such
                      other authority in India and abroad.
                    </li>
                  </ol>

                  <p>
                    You hereby agree and undertake to indemnify us, recruiters,
                    our vendors, and affiliates against all types of losses and
                    damages incurred by us due to any action taken by TRAI,
                    Access Providers (as per TRAI regulations), or any other
                    authority due to any erroneous complaint raised by you
                    against us, recruiters, our vendors, and affiliates, with
                    respect to the intimations mentioned above or due to a wrong
                    number or email ID being provided by you for any reason
                    whatsoever.
                  </p>

                  <p>
                    You may also be contacted by Service Providers with whom we
                    have entered into a contract in furtherance of our rights,
                    duties, and obligations under these documents and all other
                    policies followed by Us.
                  </p>

                  <p>
                    The sharing of the information provided by you will be
                    governed by the Privacy Policy, and We will not give out
                    such contact information of yours to third parties not
                    connected with the Software.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse6"
                  aria-expanded="false"
                  aria-controls="collapse6"
                >
                  6. INTELLECTUAL PROPERTY AND THIRD PARTY INFORMATION
                </button>
              </h2>
              <div
                id="collapse6"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    This website is the sole and exclusive property of IYS
                    Skills Tech or its licensors and vendors. We retain all
                    right, title, and interest (including all copyright,
                    trademark, patent, trade secrets, and all other intellectual
                    property rights) in the website, the tools, applications,
                    and other software being made available on the website.
                  </p>

                  <p>
                    The content that you post or provide to{' '}
                    <b>‘itsyourskills’</b>, in any manner, will become our
                    intellectual property, and you grant us the worldwide,
                    perpetual and transferable rights in such Content. We shall
                    be entitled to, consistent with Our Privacy Policy as
                    adopted in accordance with applicable law, use the Content
                    or any of its elements for any type of use forever,
                    including but not limited to promotional and advertising
                    purposes and in any media whether now known or hereafter
                    devised, including the creation of derivative works that may
                    include the Content you provide, and you shall not be
                    entitled to any payment or other compensation for such use.
                  </p>

                  <p>
                    Notwithstanding the aforementioned, you hereby expressly
                    authorize us to use the data you provide / representations
                    you make regarding your skills for our Skills Profile Engine
                    relying on the skills library.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse7"
                  aria-expanded="false"
                  aria-controls="collapse7"
                >
                  7. USER OBLIGATIONS
                </button>
              </h2>
              <div
                id="collapse7"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>You are a restricted user of this software.</p>

                  <p>
                    <strong>7.1</strong> You are bound not to distribute,
                    modify, recreate, reverse engineer, distribute, create
                    derivative works from, transfer, or sell any information of
                    the software obtained from us. With our prior permission
                    limited use may be allowed. For the removal of doubt, it is
                    clarified that unlimited or wholesale reproduction, copying
                    of the content for commercial or non-commercial purposes and
                    unwarranted modification of data and information within the
                    content of the Software is not permitted.
                  </p>

                  <p>
                    <strong>7.2</strong> You agree not to access (or attempt to
                    access) the Software and/or the materials or Services by any
                    means other than through the interface that is provided by
                    the software. The use of deep-link, robot, spider or other
                    automatic device, program, algorithm or methodology, or any
                    similar or equivalent manual process, to access, acquire,
                    copy or monitor any portion of the Software or Content, or
                    in any way reproduce or circumvent the navigational
                    structure or presentation of the Software, materials, or any
                    Content, to obtain or attempt to obtain any materials,
                    documents, or information through any means not specifically
                    made available through the Software is expressly prohibited.
                  </p>

                  <p>
                    <strong>7.3</strong> We have no obligation to monitor the
                    usage of the Software. We shall have the right to cancel the
                    membership of the users if it is found to be against the
                    applicable law or either the spirit or letter of these Terms
                    of Use. Notwithstanding this right, YOU REMAIN SOLELY
                    RESPONSIBLE FOR THE USAGE OF THE SOFTWARE.
                  </p>

                  <p>
                    <strong>7.4</strong> In places where this website allows you
                    to post or upload data/information, You undertake to ensure
                    that such material is not offensive and in accordance with
                    applicable laws. Further, You undertake not to:
                  </p>

                  <ol type="a">
                    <li>
                      Engage in any activity that interferes with or disrupts
                      access to the Website or the Services offered through the
                      site (or the servers and networks which are connected to
                      the Website);
                    </li>
                    <li>
                      Impersonate any person or entity, or falsely state or
                      otherwise misrepresent your affiliation with a person or
                      entity;
                    </li>
                    <li>
                      Publish, post, disseminate any information which is
                      grossly harmful, harassing, blasphemous, defamatory,
                      obscene, pornographic, pedophilic, libellous, invasive of
                      another’s privacy, hateful, or racially, ethnically
                      objectionable, disparaging, encouraging money laundering
                      or gambling, or otherwise unlawful in any manner whatever;
                      or unlawfully threatening or unlawfully harassing
                      including but not limited to indecently representing women
                      within the meaning of the Indecent Representation of Women
                      (Prohibition) Act, 1986;
                    </li>
                    <li>
                      Post any file that infringes the Marks of other legal
                      entities;
                    </li>
                    <li>
                      Upload or distribute files that contain viruses, corrupted
                      files, or any other similar software or programs that may
                      damage the operation of our or our vendor websites or
                      another’s computer;
                    </li>
                    <li>
                      Probe, scan or test the vulnerability of the Website or
                      any network connected to the Website, or breach the
                      security or authentication measures on the Website or any
                      network connected to the Website. You may not reverse
                      look-up, trace or seek to trace any information on any
                      other user, of or visitor to, the Website, or any other
                      customer or vendor of the website, including any website
                      Account not owned by You, to its source, or exploit the
                      Website or Service or information made available or
                      offered by or through the Website, in any way whether or
                      not the purpose is to reveal any information, including
                      but not limited to personal identification information,
                      other than Your own information, as provided for by the
                      Website;
                    </li>
                    <li>
                      Disrupt or interfere with the security of, or otherwise
                      cause harm to, the Website, systems resources, accounts,
                      passwords, servers or networks connected to or accessible
                      through the Websites or any affiliated or linked sites;
                    </li>
                    <li>
                      Collect or store data about other users in connection with
                      the prohibited conduct and activities set forth in this
                      Section;
                    </li>
                    <li>
                      Use the Website or any material or Content for any purpose
                      that is unlawful or prohibited by these Terms of Use, or
                      the laws of India, or to solicit the performance of any
                      illegal activity or other activity which infringes the
                      rights of this website or other third parties;
                    </li>
                    <li>
                      Violate any code of conduct or other guidelines, which may
                      be applicable for or to any particular Service;
                    </li>
                    <li>
                      Violate any code of conduct or other guidelines, which may
                      be applicable for or to any particular Service;
                    </li>
                    <li>
                      Publish, post, disseminate information that is false,
                      inaccurate or misleading; violate any applicable laws or
                      regulations for the time being in force in or outside
                      India;
                    </li>
                    <li>
                      Create liability for us or cause us to lose (in whole or
                      in part) the services of our internet service provider
                      (“ISPs”) our vendors or other suppliers;
                    </li>
                  </ol>

                  <p>
                    You shall not engage in advertising to, or solicitation of,
                    other Users of the Website to buy or sell any products or
                    services, except in so far as you having registered as a
                    vendor or a recruiter.
                  </p>

                  <p>
                    It shall be a violation of these Terms of Use to use any
                    information obtained from the Website in order to harass,
                    abuse, or harm another person. We can (and you hereby
                    expressly authorize us to) disclose any information about
                    you to law enforcement or other government officials, as we,
                    in our sole discretion, believe necessary or appropriate in
                    connection with the investigation and/or resolution of
                    possible crimes, especially those that may involve personal
                    injury. This may include, without limitation, disclosure of
                    the information in connection with investigation of alleged
                    illegal activity or solicitation of illegal activity or in
                    response to a lawful court order or subpoena.
                  </p>

                  <p>
                    We have no obligation to monitor the materials posted on the
                    Website. We shall have the right to remove or edit any
                    content that in our sole discretion violates or is alleged
                    to violate any applicable law or either the spirit or letter
                    of these Terms of Use. Notwithstanding this right, YOU
                    REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS
                    YOU POST ON THE WEBSITE. In no event shall we assume or have
                    any responsibility or liability for any Content posted or
                    for any claims, damages, or losses resulting from use of
                    Content and/or appearance of Content on the Website. You
                    hereby represent and warrant that you have all necessary
                    rights in and to all content which you provide, and all
                    information it contains, and that such Content shall not
                    infringe any proprietary or other rights of third parties or
                    contain any libellous, tortuous, or otherwise unlawful
                    information.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse8"
                  aria-expanded="false"
                  aria-controls="collapse8"
                >
                  8. DISCLAIMER OF WARRANTIES AND LIABILITIES
                </button>
              </h2>
              <div
                id="collapse8"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    YOU EXPRESSLY UNDERSTAND AND AGREE THAT, TO THE MAXIMUM
                    EXTENT PERMITTED BY APPLICABLE LAW:
                  </p>

                  <p>
                    THE SOFTWARE, SERVICES, AND OTHER MATERIALS ARE PROVIDED BY
                    THIS SOFTWARE ON AN “AS IS” BASIS WITHOUT WARRANTY OF ANY
                    KIND, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING
                    THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT,
                    MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
                    WITHOUT LIMITING THE FOREGOING, WE MAKE NO WARRANTY THAT
                  </p>

                  <ol>
                    <li>
                      (I) YOUR REQUIREMENTS WILL BE MET OR THAT SERVICES
                      PROVIDED WILL BE UNINTERRUPTED, TIMELY, SECURE, OR
                      ERROR-FREE;
                    </li>
                    <li>
                      (II) MATERIALS, INFORMATION OBTAINED AND RESULTS WILL BE
                      EFFECTIVE, ACCURATE OR RELIABLE;
                    </li>
                    <li>
                      (III) ANY ERRORS OR DEFECTS IN THE SOFTWARE OR SERVICES
                      WILL BE MODIFIED.
                    </li>
                    <li>
                      (IV) THE EMPLOYMENTS MADE AVAILABLE THROUGH OUR VENDORS /
                      RECRUITERS SHALL BE AVAILABLE THROUGHOUT THE YEAR OR
                      AVAILABLE AT ALL TIMES;
                    </li>
                  </ol>

                  <p>
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE WILL
                    HAVE NO LIABILITY RELATED TO USER CONTENT ARISING UNDER
                    INTELLECTUAL PROPERTY RIGHTS, PRIVACY, PUBLICITY, OR OTHER
                    LAWS. THE WEBSITE ALSO DISCLAIMS ALL LIABILITY WITH RESPECT
                    TO THE MISUSE, LOSS, MODIFICATION, OR UNAVAILABILITY OF ANY
                    USER CONTENT.
                  </p>

                  <p>
                    THE USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA
                    DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE WEBSITE IS DONE
                    ENTIRELY AT THEIR OWN DISCRETION AND RISK. THE WEBSITE
                    ACCEPTS NO LIABILITY FOR ANY ERRORS OR OMISSIONS, WITH
                    RESPECT TO ANY INFORMATION PROVIDED TO YOU WHETHER ON BEHALF
                    OF ITSELF OR THIRD PARTIES.
                  </p>

                  <p>
                    WE SHALL NOT BE LIABLE FOR DELAYS OR INABILITIES IN
                    PERFORMANCE OR NON-PERFORMANCE IN WHOLE OR IN PART OF VENDOR
                    / RECRUITER / USER OBLIGATIONS.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse9"
                  aria-expanded="false"
                  aria-controls="collapse9"
                >
                  9. INDEMNIFICATION AND LIMITATION OF LIABILITY
                </button>
              </h2>
              <div
                id="collapse9"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS THIS
                    WEBSITE INCLUDING BUT NOT LIMITED TO ITS AFFILIATE VENDORS,
                    AGENTS AND EMPLOYEES FROM AND AGAINST ANY AND ALL LOSSES,
                    LIABILITIES, CLAIMS, DAMAGES, DEMANDS, COSTS AND EXPENSES
                    (INCLUDING LEGAL FEES AND DISBURSEMENTS IN CONNECTION
                    THEREWITH AND INTEREST CHARGEABLE THEREON) ASSERTED AGAINST
                    OR INCURRED BY US THAT ARISE OUT OF, RESULT FROM, OR MAY BE
                    PAYABLE BY VIRTUE OF, ANY BREACH OR NON-PERFORMANCE OF ANY
                    REPRESENTATION, WARRANTY, COVENANT OR AGREEMENT MADE OR
                    OBLIGATION TO BE PERFORMED BY YOU PURSUANT TO THESE TERMS OF
                    USE, OR ANY OTHER ACTION INCURRED BY YOU AS A RESULT OF
                    USING THE WEBSITE. FURTHER, YOU AGREE TO HOLD US HARMLESS
                    AGAINST ANY CLAIMS MADE BY ANY THIRD PARTY DUE TO, OR
                    ARISING OUT OF, OR IN CONNECTION WITH, YOUR USE OF THE
                    WEBSITE, YOUR USE OF THE SERVICES OFFERED, ANY CLAIM THAT
                    YOUR MATERIAL CAUSED DAMAGE TO A THIRD PARTY, YOUR VIOLATION
                    OF THE TERMS OF USE, OR YOUR VIOLATION OF ANY RIGHTS OF
                    ANOTHER, INCLUDING ANY INTELLECTUAL PROPERTY RIGHTS. THE
                    USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA
                    DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE SOFTWARE IS
                    DONE ENTIRELY AT THEIR OWN DISCRETION AND RISK. WE ARE NOT
                    RESPONSIBLE FOR ANY TYPOGRAPHICAL ERROR IN THE DETAILS SHOWN
                    / PRODUCED ON THE PORTAL AND WE ACCEPT NO LIABILITY FOR ANY
                    ERRORS OR OMISSIONS, WITH RESPECT TO ANY INFORMATION
                    PROVIDED TO YOU WHETHER ON BEHALF OF OURSELF OR THIRD
                    PARTIES. THE LIMITATIONS AND EXCLUSIONS IN THIS SECTION
                    APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. IF,
                    DESPITE THE LIMITATION ABOVE, WE ARE FOUND LIABLE FOR ANY
                    LOSS OR DAMAGE WHICH ARISES OUT OF OR IS IN ANY WAY
                    CONNECTED WITH ANY OF THE OCCURRENCES DESCRIBED IN THE
                    LIMITATION ABOVE, THEN OUR LIABILITY WILL IN NO EVENT
                    EXCEED, IN TOTAL, THE SUM OF INR 5,000.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse10"
                  aria-expanded="false"
                  aria-controls="collapse10"
                >
                  10. TERMINATION
                </button>
              </h2>
              <div
                id="collapse10"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    IYS Skills Tech, in its sole discretion, may, at any time
                    and without advance notice or liability, terminate or
                    restrict your access to all or any component of our Site,
                    even if access continues to be allowed to others. Upon such
                    termination or suspension, you must immediately discontinue
                    use of the Site, and destroy any copy you have made of any
                    portion of the Site. Accessing the Site after such
                    termination, suspension or discontinuation shall constitute
                    an act of trespassing. We shall not be accountable to you to
                    such suspension or termination.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse11"
                  aria-expanded="false"
                  aria-controls="collapse11"
                >
                  11. HOSTING OF THIRD PARTY INFORMATION
                </button>
              </h2>
              <div
                id="collapse11"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    The website hosts information provided by third parties that
                    is intended for informational purposes only. We are in no
                    way responsible to you for the accuracy and legitimacy of
                    the information so hosted. We take reasonable care to ensure
                    such accuracy but, you agree to not hold us liable for the
                    falsification of any such provided information. You are
                    responsible for evaluating the accuracy, completeness, and
                    usefulness of any opinion, advice or other content available
                    through the website or obtained from a linked site.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse12"
                  aria-expanded="false"
                  aria-controls="collapse12"
                >
                  12. VIRUSES
                </button>
              </h2>
              <div
                id="collapse12"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    We make reasonable attempts to clear the website of viruses
                    and worms, but cannot ensure that the Site will be at all
                    times free from viruses or other destructive software. You
                    are urged to take appropriate safeguards before downloading
                    any information from the Site. We accept no responsibility
                    for any damages to computer equipment or other property
                    which may result from use of the website or downloading
                    anything from the website.
                  </p>
                </div>
              </div>
            </div>
            <div className="accordion-item mb-5 border-0 border-bottom">
              <h2 className="accordion-header">
                <button
                  className="accordion-button collapsed fs-5"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapse13"
                  aria-expanded="false"
                  aria-controls="collapse13"
                >
                  13. DISPUTES
                </button>
              </h2>
              <div
                id="collapse13"
                className="accordion-collapse collapse"
                data-bs-parent="#accordionExample"
              >
                <div className="accordion-body">
                  <p>
                    If any dispute arises between you and IYS Skills Tech during
                    your use of the Site or thereafter, in connection with the
                    validity, interpretation, implementation or alleged breach
                    of any provision of the Terms and Conditions, the dispute
                    shall be referred to a sole Arbitrator who shall be
                    appointed by us. The place of arbitration shall be Chennai.
                    The arbitration proceedings shall be in the English
                    language.
                  </p>
                  <p>
                    The Terms and Conditions shall be governed and construed in
                    accordance with the Indian laws.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Newsletter title="Have more questions?" />
      </div>
    </div>
  );
};

export default Content;
