# Generated by Django 4.2.1 on 2023-06-06 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("profile", "isot_file_id")},
        ),
    ]
