# Generated by Django 4.2.1 on 2023-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0002_alter_skill_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillprofile",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
