# Generated by Django 4.2.3 on 2023-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0003_skillprofile_is_shared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="rating",
        ),
        migrations.AddField(
            model_name="skill",
            name="ratings",
            field=models.JSONField(default=list),
        ),
    ]
