# Generated by Django 4.2.3 on 2023-10-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0004_alter_skill_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="skill",
            name="isot_path_addr",
            field=models.CharField(default="103628.103611.103606", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("profile", "isot_path_addr")},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="isot_file_id",
        ),
    ]
