# Generated by Django 4.2.3 on 2024-02-25 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0005_alter_skill_unique_together_skill_isot_path_addr_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="skill",
            name="profile",
        ),
    ]
