# Generated by Django 4.2.3 on 2024-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0006_alter_skill_unique_together_remove_skill_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillprofile",
            name="skills",
            field=models.ManyToManyField(
                related_name="skill_profiles", to="profilers.skill"
            ),
        ),
    ]
