# Generated by Django 4.2.3 on 2024-02-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0007_skillprofile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillprofile",
            name="skills",
            field=models.ManyToManyField(related_name="profile", to="profilers.skill"),
        ),
    ]
