# Generated by Django 4.2.3 on 2024-02-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0008_alter_skillprofile_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewProfileUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("about", models.TextField()),
                ("linkedin_url", models.URLField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_profile_users",
                        to="profilers.skillprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ratings", models.JSONField(default=list)),
                (
                    "review_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_skills",
                        to="profilers.reviewprofileusers",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_skills",
                        to="profilers.skill",
                    ),
                ),
            ],
        ),
    ]
