# Generated by Django 4.2.3 on 2024-02-26 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0009_reviewprofileusers_reviewskills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReviewProfileUsers",
            new_name="ReviewProfileUser",
        ),
    ]
