# Generated by Django 4.2.3 on 2024-02-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0010_rename_reviewprofileusers_reviewprofileuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewprofileuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("IS", "Indirect Seniors"),
                    ("JR", "Junior"),
                    ("SR", "Seniors"),
                    ("PR", "Peers"),
                ],
                default="PR",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
