# Generated by Django 4.2.3 on 2024-02-27 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0011_reviewprofileuser_user_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewprofileuser",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterUniqueTogether(
            name="reviewprofileuser",
            unique_together={("profile", "email")},
        ),
    ]
