# Generated by Django 4.2.3 on 2024-02-27 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0012_alter_reviewprofileuser_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewprofileuser",
            unique_together=set(),
        ),
    ]
