# Generated by Django 4.2.3 on 2024-02-27 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0013_alter_reviewprofileuser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewprofileuser",
            unique_together={("profile", "email")},
        ),
    ]
