# Generated by Django 4.2.3 on 2024-03-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0014_alter_reviewprofileuser_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewprofileuser",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
