# Generated by Django 4.2.3 on 2024-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profilers", "0015_reviewprofileuser_is_submitted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewprofileuser",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewprofileuser",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
