# Generated by Django 4.2.3 on 2024-08-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilers', '0016_alter_reviewprofileuser_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.CharField(default='default', max_length=1000),
        ),
    ]
