from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import generate_assessment,jobfit_generate_assessment,jobfit_fetch_interview_link,save_translated_questions,jobfit_verify_email,jobfit_interview_link,skills_generate_assessment,skills_pause_assessment,skills_submit_paper,skills_resume_voice, submit_assessment, generate_assessment_new,submit_assessment_new, discipline_list,respond_to_notifications, level_of_education_list, get_states, get_countries, get_cities, save_job_profile, get_job_titles, submit_job_background_profile, retrieve_job_background_details, get_user_rated_skills, shortlist_profiles, get_shortlisted_profiles, save_request_details, get_notifications, get_closed_messages, fetch_conversations, fetch_messages, send_message, reject_reason, save_candidate_profile, get_candidate_details, delete_job, get_job_rated_skills, update_job_profile, get_assessment_result, interview_link, verify_email, save_initial_voice, saving_resume_voice, submit_paper, pause_paper, save_answer, skills_interview_link, skills_saving_initial_voice

app_name = "profilers"
urlpatterns = [
    path("render-pdf-view/", views.render_pdf_view, name="render_pdf_view"),
    path("api-get-files/", views.api_get_files, name="api_get_files"),
    path("api-search/", views.api_search, name="api_search"),
    path(
        "get-shared-user-skills/<str:share_id>/",
        views.get_shared_user_skills,
        name="get_shared_user_skills",
    ),
    path(
        "view-skills-profile/<str:alpha_num_str>/",
        views.view_mode_skills_profile,
        name="view_mode_skills_profile",
    ),
    path(
        "embed-view-skills-profile/<str:alpha_num_str>/",
        views.embed_view_mode_skills_profile,
        name="embed_view_mode_skills_profile",
    ),
    # path("my-skills-profile/tree-view/", views.my_skills_profile_tree_view, name="my_skills_profile_tree_view"),
    # path("my-skills-profile/bubble-view/", views.my_skills_profile_bubble_view, name="my_skills_profile_bubble_view"),
    path("api-child/", views.api_child, name="api_child"),
    path("api-tree/", views.api_tree, name="api_tree"),
    path("save-profile/", views.save_profile, name="save_profile"),
    path("delete-skill/<str:skill_id>/", views.delete_skill, name="save_profile"),
    path(
        "api-popular-categories/",
        views.api_popular_categories,
        name="api_popular_categories",
    ),
    path("add-skills/", views.add_skills, name="add_skills"),
    path("get-skills/", views.get_skills, name="get_skill"),
    path(
        "add-review-user/",
        views.CreateReviewProfileUserView.as_view(),
        name="add_review_user",
    ),
    path(
        "review-user/profile/<str:review_user_token>/",
        views.GetSkillsForReviewUserView.as_view(),
        name="get_all_skills_profile_review_user",
    ),
    path(
        "review-user/profile/submit/<str:review_user_token>/",
        views.SubmitSkillsForReviewUserView.as_view(),
        name="submit_all_skills_profile_review_user",
    ),
    path(
        "get-peers-feedback/",
        views.GetPeersFeedback.as_view(),
        name="get_peers_feedback",
    ),
    path('generate-assessment/', generate_assessment, name='generate_assessment'),
    path('vani-generate-assessment/', generate_assessment_new, name='generate_assessment'),
    path('submit-assessment/', submit_assessment, name='submit_assessment'),
    path('vani-submit-assessment/', submit_assessment_new, name='submit_assessment'),
    path('api/discipline/', discipline_list, name='discipline-list'),
    path('api/level-of-education/', level_of_education_list, name='level-of-education-list'),
    path('api/countries/', get_countries, name='get_countries'),
    path('api/states/<int:country_id>/', get_states, name='get_states'),
    path('api/cities/<int:country_id>/<int:state_id>/', get_cities, name='get_cities'),
    #path('api/states/', get_states, name='get_states'),
    # path("bubble-view/", views.bubble_view, name="bubble_view"),
    # path("tree-view/", views.tree_view, name="tree_view"),
    # path("tile-view/", views.tile_view, name="tile_view"),
    path('save-job-profile/', save_job_profile, name='save_job_profile'),
    path('job-titles/<user_id>/', get_job_titles, name='get_job_titles'),
    path('submit-job-background-profile/', submit_job_background_profile, name='submit_job_background_profile'),
    path('retrieve-job-background-details/<user_id>/<id>/', retrieve_job_background_details, name='retrieve_job_background_details'),
    path('get-user-rated-skills/<user_id>/<id>/', get_user_rated_skills, name='get_user_rated_skills'),
    path('shortlist-profiles/', shortlist_profiles, name='shortlist_profiles'),
    path('get-shortlisted-profiles/<user_id>/<id>/', get_shortlisted_profiles, name='get_shortlisted_profiles'),
    path('initiate-message/', save_request_details, name='initiate_message'),
    path('notifications/<receiver_id>/', get_notifications, name='get_notifications'),
    path('closed-messages/<receiver_id>/', get_closed_messages, name='get_closed_messages'),
    path('notification-responds/', respond_to_notifications, name='respond_notification'),
    path('messages/conversations/<individual_profile_id>/', fetch_conversations, name='fetch_conversations'),
    path('messages/<sender_id>/<receiver_id>/', fetch_messages, name='fetch_messages'),
    path('messages/send/', send_message, name='send_message'),
    path('notifications/reject-reason/', reject_reason, name='reject_reason'),
    path('job-background-status/<str:user_id>/<str:job_id>/', views.check_job_background_status, name='check_job_background_status'),
    path('save-candidate-profile/', save_candidate_profile, name='save_candidate_profile'),
    path('get-candidate-details/<str:job_id>/', get_candidate_details, name='get_candidate_details'),
    path('delete/jsp/<str:id>/', delete_job, name='delete_job'),
    path('get-job-rated-skills/<str:id>/', get_job_rated_skills, name='get_job_rated_skills'),
    path('update-job-profile/', update_job_profile, name='update_job_profile'),
    path('assessments/<str:individual_profile_id>/', get_assessment_result, name='get_assessment_result'),
    path("generate-job-assessment/", views.generate_questions, name="generate_questions"),
    path("fetch/<str:token>/", views.fetch_assessment, name="fetch_assessment"),
    path("submit-job-assessment/", views.submit_job_assessment, name="submit_assessment"),
    path("get-job-assessment/<str:recruiter_id>/", views.get_job_assessment, name="get-job-assessment"),
    path("recruiter-assessment/<str:recruiter_id>/", views.get_recruiter_assessment, name="get_recruiter_assessment"),
    path("interview-link/<str:token>/", interview_link, name="interview_link"),
    path("verify-email/<str:token>/", verify_email, name="verify_email"),
    path("initial-voice/<str:token>/", save_initial_voice, name="save_initial_voice"),  # URL for saving initial voice
    path("resume-voice/<str:token>/", saving_resume_voice, name="saving_resume_voice"),  # URL for saving resume voice
    path("save-answer/<str:token>/<int:question_id>/", save_answer, name="save_answer"),
    path("submit-paper/<str:token>/", submit_paper, name="submit_paper"),
    path("pause/<str:token>/", pause_paper, name="pause_paper"),
    path('skills/generate-assessment/', skills_generate_assessment, name='skills_generate_assessment'),
    path("skills/interview_link/<str:token>/", skills_interview_link, name="skills_interview_link"),
    path("skills/initial_voice/<str:token>/", skills_saving_initial_voice, name="skills_saving_initial_voice"),
    path("skills/resume_voice/<str:token>/", skills_resume_voice, name="skills_resume_voice"),
    path("skills/save_answer/<str:token>/<int:question_id>/", views.skills_save_answer, name="skills_save_answer"),
    path("skills/save_translated_questions/<str:token>/", views.skills_save_translated_questions, name="skills_save_translated_questions"),
    path("skills/submit/<str:token>/", skills_submit_paper, name="skills_submit_paper"),
    path("skills/pause/<str:token>/", skills_pause_assessment, name="skills_pause-assessment"),
    path("", views.home, name="home"),
    path("voices/", views.get_voices, name="voices"),
    path("tts/", views.tts, name="tts"),
    path("translate/", views.translate, name="translate"),
    path("presign_upload/", views.presign_upload, name="presign_upload"),
    path('jobfit/generate-assessment/', jobfit_generate_assessment, name='jobfit_generate_assessment'),
    path('jobfit/fetch-interview-link/', jobfit_fetch_interview_link, name='jobfit_fetch_interview_link'),
    path("jobfit/interview_link/<str:token>/", jobfit_interview_link, name="jobfit_interview_link"),
    path("jobfit/verify/<str:token>/", jobfit_verify_email, name="jobfit_verify_email"),
    path("jobfit/initial_voice/<str:token>/", save_initial_voice, name="save_initial_voice"),
    path("jobfit/resume_voice/<str:token>/", saving_resume_voice, name="saving_resume_voice"),
    path("jobfit/save_answer/<str:token>/<int:question_id>/", save_answer, name="save_answer"),
    path("jobfit/save_translated_questions/<str:token>/", save_translated_questions, name="save_answer"),
    path("jobfit/submit/<str:token>/", submit_paper, name="submit_paper"),
    path("jobfit/pause/<str:token>/", pause_paper, name="pause_paper"),





      # URL for save_answer API
]
