# Generated by Django 4.2.3 on 2024-04-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Phone Number"
            ),
        ),
    ]
