# Generated by Django 4.2.3 on 2024-08-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_payment_complete_user_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_for',
            field=models.JSONField(default=list),
        ),
    ]
