# Generated by Django 4.2.3 on 2024-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_paid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid_for',
            field=models.JSONField(default=list),
        ),
    ]
